src/core/urls.py
"""sparesnack base URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("foods.urls")),
    path("accounts/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore

src/users/urls.py
"""
URL configuration for the users app
"""

from importlib import import_module

from allauth.account import views as auth_views
from allauth.socialaccount import providers
from django.conf import settings
from django.urls import include, path

from users import views

urlpatterns = [
    path("profile/", views.profile, name="account_profile"),
    path("signup/", auth_views.signup, name="account_signup"),
    path("login/", auth_views.login, name="account_login"),
    path("logout/", views.logout, name="account_logout"),
    path(
        "password/change/",
        auth_views.password_change,
        name="account_change_password",
    ),
    path(
        "profile/goals",
        views.change_goals,
        name="account_change_goals",
    ),
    path(
        "profile/avatar",
        views.change_avatar,
        name="account_change_avatar",
    ),
]

if "allauth.socialaccount" in settings.INSTALLED_APPS:
    urlpatterns += [path("social/", include("allauth.socialaccount.urls"))]

provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + ".urls")
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, "urlpatterns", None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns

urlpatterns += provider_urlpatterns

src/users/models.py
"""Models for the users app"""

from typing import Any
from django.contrib.auth.models import User
from django.db import models
from django_resized import ResizedImageField

from core.utils import UploadAndRename, image_clean_up


class Profile(models.Model):
    """A profile for the user to change his preferences"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_metric = models.BooleanField(default=True)
    fats = models.FloatField(default=0)
    protein = models.FloatField(default=0)
    carbs = models.FloatField(default=0)
    image = ResizedImageField(
        size=[160, 160],
        default="users/default_avatar.png",
        upload_to=UploadAndRename("users/profile_pictures"),
    )

    def __str__(self) -> str:
        """Additional data for debugging"""
        return f"{self.user.username}'s Profile"

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Clean up after the old image if we have a new one"""
        image_clean_up(self)
        super().save(*args, **kwargs)

src/users/views.py
"""Views concerning the user"""
from typing import Any, Optional, cast
from allauth.account.views import LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.query import QuerySet
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render
from django.urls.base import reverse_lazy
from django.views.generic.base import View
from django.views.generic.edit import UpdateView

from foods.models import Diet, Meal
from users.models import Profile


class UserProfileView(View):
    """View for showing the user his/her profile"""

    template_name = "profile/index.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        """Update the request with the logged in user to display his data"""
        context = {
            "user": request.user,
            "meals": Meal.objects.filter(author=cast(User, self.request.user)),
            "diets": Diet.objects.filter(author=cast(User, self.request.user)),
        }
        from django.db import connection

        return render(request, self.template_name, context=context)


profile = login_required(UserProfileView.as_view())


class ProperLogoutView(LogoutView):
    """Override the default redirect url for the logout view"""

    def get_redirect_url(self) -> str:  # pylint: disable=no-self-use
        """Let's redirect to our logout_done view"""
        return reverse_lazy("foods_meal_browse")


logout = login_required(ProperLogoutView.as_view())


class ChangeGoalsView(SuccessMessageMixin, UpdateView):
    """Change preferred amounts of fats, sugars and carbs"""

    model = Profile
    template_name = "profile/change_goals.html"
    context_object_name = "profile"
    fields = ("fats", "protein", "carbs")
    success_url = reverse_lazy("account_profile")
    success_message = "The preferences have been changed"

    def get_object(self, queryset: Optional[QuerySet[Any]] = None) -> Profile:
        """Return the user profile instance"""
        user = cast(User, self.request.user)
        return Profile.objects.get(user=user)


change_goals = login_required(ChangeGoalsView.as_view())


class ChangeAvatarView(SuccessMessageMixin, UpdateView):
    """Change the avatar of the user"""

    model = Profile
    template_name = "profile/change_avatar.html"
    context_object_name = "profile"
    fields = ("image",)
    success_url = reverse_lazy("account_profile")
    success_message = "The avatar image has been changed"

    def get_object(self, queryset: Optional[QuerySet[Any]] = None) -> Profile:
        """Return the user profile instance"""
        user = cast(User, self.request.user)
        return Profile.objects.get(user=user)


change_avatar = login_required(ChangeAvatarView.as_view())

src/users/templates/profile/change_avatar.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="icon" href="{% static '/img/favicon.ico' %}">
		<title>Avatar - SpareSnack</title>
		<link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alata">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin:400,700">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static '/fonts/fontawesome5-overrides.min.css' %}">
		<link rel="stylesheet" href="{% static '/css/first.css' %}">
	</head>
	<body class="bg-gradient-primary" style="background-image: linear-gradient(180deg, var(--bg1) 10%, var(--vector__tertiary));background-color: var(--bg1);">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-9 col-lg-12 col-xl-10">
					<div class="card shadow-lg o-hidden border-0 my-5">
						<div class="card-body p-0">
							<div class="row">
								<div class="col-lg-6 d-none d-lg-flex">
									<div class="flex-grow-1 bg-login-image" style="background-image: url(&quot;{% static '/img/login.jpg' %}&quot;);");"></div>
								</div>
								<div class="col-lg-6">
									<div class="p-5">
										<div class="text-center">
											<h4 class="text-dark mb-4">Change your avatar</h4>
										</div>
										<form class="user" method="POST" enctype="multipart/form-data">
											{% csrf_token %}
											<div class="row">
												<div class="col-lg-6 mx-auto">
													<!-- Upload image input-->
													<div class="input-group mb-3 rounded-pill bg-white">
														<input id="upload" name="image" type="file" class="form-control border-0">
													</div>
												</div>
											</div>
											<hr><button class="btn btn-primary btn-block text-white btn-google btn-user" type="submit" style="background: var(--purple);"><i class="fas fa-user-tie"></i>&nbsp;Change avatar</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
		<script src="{% static '/js/general/theme.js' %}"></script>
	</body>
</html>

src/users/templates/profile/change_goals.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="icon" href="{% static '/img/favicon.ico' %}">
		<title>Goals - SpareSnack</title>
		<link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alata">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin:400,700">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static '/fonts/fontawesome5-overrides.min.css' %}">
		<link rel="stylesheet" href="{% static '/css/first.css' %}">
	</head>
	<body class="bg-gradient-primary" style="background-image: linear-gradient(180deg, var(--bg1) 10%, var(--vector__tertiary));background-color: var(--bg1);">
		<div class="container">
			<div class="card shadow-lg o-hidden border-0 my-5">
				<div class="card-body p-0">
					<div class="row">
						<div class="col-lg-5 d-none d-lg-flex">
							<div class="flex-grow-1 bg-register-image" style="background-image: url(&quot;{% static '/img/login.jpg' %}&quot;);"></div>
						</div>
						<div class="col-lg-7">
							<div class="p-5">
								<div class="text-center">
									{% if messages %}
									{% for message in messages %}
									<p>{{message}}</p>
									{% endfor %}
									{% endif %}
									<h4 class="text-dark mb-4">Change your caloric goals</h4>
								</div>
								<form method="POST" action="{% url 'account_change_goals' %}" class="user">
									{% csrf_token %}
									<div class="form-group row" style="width: 100%;">
										<label for="id_fats">Fats</label>
										<input class="form-control form-control-user" id="id_fats" type="number" step="any" value="{{ profile.fats }}" name="fats" placeholder="" required="" style="margin-left: 3%;">
									</div>
									<div class="form-group row" style="width: 100%;">

										<label for="id_protein">Protein</label>
										<input class="form-control form-control-user" id="id_protein" type="number" step="any" value="{{ profile.protein }}" name="protein" placeholder="" required="" style="margin-left: 3%;">
									</div>
									<div class="form-group row" style="width: 100%;">

										<label for="id_carbs">Carbs</label>
										<input class="form-control form-control-user" id="id_carbs" type="number" step="any" value="{{ profile.carbs }}" name="carbs" placeholder="" required="" style="margin-left: 3%;">
									</div>
									<button class="btn btn-primary btn-block text-white btn-user" style="background-color: var(--btn);border-color: var(--btn);" type="submit" name="action">Change!</button>
									<hr>
								</form>
								<div class="text-center"></div>
								<div class="text-center"><a class="small" href="{% url 'foods_day_create' %}">My day</a></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
		<script src="{% static '/js/general/theme.js' %}"></script>
	</body>
</html>

src/users/templates/profile/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="icon" href="{% static '/img/favicon.ico' %}">
		<title>Profile - SpareSnack</title>
		<link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alata">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin:400,700">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static '/fonts/fontawesome5-overrides.min.css' %}">
		<link rel="stylesheet" href="{% static '/css/first.css' %}">
	</head>
	<body id="page-top">
		<div id="wrapper">
			<nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0" style="background-image: linear-gradient(180deg, var(--bg1) 10%, var(--vector__tertiary));background-color: var(--bg1);">
				<div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{% url 'foods_home' %}">
						<div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-pepper-hot"></i></div>
						<div class="sidebar-brand-text mx-3" style="text-transform: capitalize;font-family: Cabin, sans-serif;"><span style="font-family: Alata, sans-serif;">spareSnack</span></div>
					</a>
					<hr class="sidebar-divider my-0">
					<ul class="navbar-nav text-light" id="accordionSidebar">
						<li class="nav-item"><a class="nav-link" href="{% url 'foods_day_create' %}"><i class="fa fa-home"></i><span style="font-family: Alata, sans-serif;">My day</span></a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'foods_meal_create' %}"><i class="fas fa-table"></i><span style="font-family: Alata, sans-serif;">Meals</span></a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'foods_diet_browse' %}"><i class="fa fa-th-list"></i><span style="font-family: Alata, sans-serif;">Diets</span></a></li>
					</ul>
					<div class="text-center d-none d-md-inline"></div>
				</div>
			</nav>
			<div class="d-flex flex-column" id="content-wrapper">
				<div id="content">
					<nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
						<div class="container-fluid">
							{% for message in messages %}
							<div style="margin-right: 2%;box-shadow: 6px 6px 4px #e5e5e5;border: hidden;padding: 1%;display: grid;background: #e9f4f4;border-radius: 9px;">
								<div class="info" style="align-items: center;display: flex;"><span style="margin: 1px;color: #404040;font-family: Alata, sans-serif;font-size: 14px;">{{ message }}</span></div>
							</div>
							{% endfor %}
							<ul class="navbar-nav flex-nowrap ml-auto">
								<li class="nav-item dropdown no-arrow">
									<div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><span class="d-none d-lg-inline mr-2 text-gray-600 small">{{ request.user.username }}</span><img class="border rounded-circle img-profile" src="{{ request.user.profile.image.url }}"></a>
										<div class="dropdown-menu shadow dropdown-menu-right animated--grow-in"><a class="dropdown-item" href="{% url 'account_profile' %}"><i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Profile</a>
											<div class="dropdown-divider"></div><a class="dropdown-item" href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Logout</a>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</nav>
					<div class="container-fluid">
						<h3 class="text-dark mb-4">Profile - {{ user.username }}</h3>
						<div class="row mb-3">
							<div class="col-lg-4">
								<div class="card mb-3">
									<div class="card-body text-center shadow"><img class="rounded-circle mb-3 mt-4" src="{{ user.profile.image.url }}" width="160" height="160" style="width: 160px;height: 160px;">
										<div class="mb-3">
											<a class="btn btn-primary btn-sm" href="{% url 'account_change_password' %}" style="background: var(--purple);">Change Password</a>
											<a class="btn btn-primary btn-sm" href="{% url 'account_change_avatar' %}" style="background: var(--purple);">Change Avatar</a>
										</div>
									</div>
								</div>
								<div class="card shadow mb-4">
									<div class="card-header py-3">
										<h6 class="text-primary font-weight-bold m-0" style="color: var(--p)!important;">My current goals</h6>
									</div>
									<div class="card-body">
										<h4 class="small font-weight-bold">Fats<span class="float-right">{{ user.profile.fats }}kcal</span></h4>
										<h4 class="small font-weight-bold">Carbohydrates<span class="float-right"><strong>{{ user.profile.carbs }}kcal</strong></span></h4>
										<h4 class="small font-weight-bold">Protein<span class="float-right"><strong>{{ user.profile.protein }}kcal</strong></span></h4>
										<div class="mb-3" style="margin-top: 7%;text-align: center;"><a class="btn btn-primary btn-sm" href="{% url 'account_change_goals' %}" style="background: var(--purple);">Change Preferences</a></div>
									</div>
								</div>
							</div>
							<div class="col-lg-8">
								<div class="row">
									<div class="col">
										<div class="card shadow mb-3">
											<div class="card-header py-3">
												<p class="text-primary m-0 font-weight-bold" style="color: var(--p)!important;">My diets</p>
											</div>
											<ul class="list-group list-group-flush">
												{% for diet in diets %}
												<li class="list-group-item">
													<div class="row align-items-center no-gutters">
														<div class="col mr-2">
															<h6 class="mb-0"><strong>{{ diet.name }}</strong></h6><a class="text-dark text-xs" href="{{ diet.get_absolute_url }}">{{ diet.description }}</a>
														</div>
														<div class="col-auto"><a class="text-dark" href="{{ diet.get_absolute_url }}"><i class="far fa-star"></i></a></div>
													</div>
												</li>
												{% endfor %}
											</ul>
										</div>
										<div class="card shadow">
											<div class="card-header py-3">
												<p class="text-primary m-0 font-weight-bold" style="color: var(--p)!important;">My meals</p>
											</div>
											<ul class="list-group list-group-flush">
												{% for meal in meals %}
												<li class="list-group-item">
													<div class="row align-items-center no-gutters">
														<div class="col mr-2">
															<h6 class="mb-0"><strong>{{ meal.name }}</strong></h6><a class="text-dark text-xs" href="{{ meal.get_absolute_url }}">{{ meal.description }}</a>
														</div>
														<div class="col-auto"><a class="text-dark" href="{{ meal.get_absolute_url }}"><i class="far fa-star"></i></a></div>
													</div>
												</li>
												{% endfor %}
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<footer class="bg-white sticky-footer">
					<div class="container my-auto">
						<div class="text-center my-auto copyright"><span>Copyright © TypicalAM 2022</span></div>
					</div>
				</footer>
			</div>
		</div>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
		<script src="{% static '/js/general/theme.js' %}"></script>
	</body>
</html>