src/core/urls.py
"""sparesnack base URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("foods.urls")),
    path("accounts/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore

src/foods/urls.py
"""
URL configuration for the diet app -
for example the link to browse would be 'example.com/diet/browse'
"""

from django.urls import path

from foods.views import diet_views, meal_views

urlpatterns = [
    path("", meal_views.homepage_view, name="foods_home"),
    path("day/create/", meal_views.day_create, name="foods_day_create"),
    path("meals/create/", meal_views.create, name="foods_meal_create"),
    path("meals/browse/", meal_views.browse, name="foods_meal_browse"),
    path("meals/<pk>/", meal_views.detail, name="foods_meal_detail"),
    path("meals/<pk>/delete/", meal_views.delete, name="foods_meal_delete"),
    path("diet/create/", diet_views.create, name="foods_diet_create"),
    path("diet/browse/", diet_views.browse, name="foods_diet_browse"),
    path("diet/<slug>/import/", diet_views.imprt, name="foods_diet_import"),
    path("diet/<slug>/", diet_views.detail, name="foods_diet_detail"),
    path("diet/<slug>/delete/", diet_views.delete, name="foods_diet_delete"),
]

src/foods/models.py
"""Models for the foods app"""
import datetime
from typing import Any, Sequence

from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE
from django.template.defaultfilters import slugify
from django.urls.base import reverse
from django_resized import ResizedImageField

from core.utils import UploadAndRename, image_clean_up


class Ingredient(models.Model):
    """Ingredients are a part of meals, they dictate the amount of calories in a meal"""

    name = models.CharField(max_length=100)
    measure_type = models.CharField(max_length=50)
    convert_rate = models.FloatField(default=1)
    fats = models.FloatField(default=0)
    protein = models.FloatField(default=0)
    carbs = models.FloatField(default=0)
    image = ResizedImageField(
        size=[200, 200],
        default="foods/default_ingredient_thumbnail.jpg",
        upload_to=UploadAndRename("foods/ingredient_thumbnails"),
    )

    def __str__(self) -> str:
        return f"{self.name} measured with {self.measure_type} at {self.convert_rate}g per 1 item"

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Clean up after the old image if we have a new one"""
        image_clean_up(self)
        super().save(*args, **kwargs)

    def get_base_calories(self) -> int:
        """Get the calories for 100 grams of a certain food"""
        return round(self.fats * 8 + self.protein * 4 + self.carbs * 4)

    def convert_from_grams(self, grams: float) -> float:
        """Display to the user the amount of the item, having the item in grams

        Example:    Mango.measure_type = FRUITS
                    Mango.convert_rate = 300
                    if grams is 600 we are returning '2 FRUITS'

                    Sugar.measure_type = TBSP
                    Sugar.convert_rate = 15
                    if grams is 45 we are returning '3 TBSP'
        """
        return round(grams / self.convert_rate, 2)

    def convert_to_grams(self, quantity: float) -> float:
        """A function analogous to `convert_from_grams`

        Example:    Mango.measure_type = FRUITS
                    Mango.convert_rate = 300
                    if quantity is 2 we are returning '600 grams'

                    Sugar.measure_type = TBSP
                    Sugar.convert_rate = 15
                    if quantity is 4 we are returning '60 grams'
        """
        return round(quantity * self.convert_rate)


class Meal(models.Model):
    """Meals have ingredients, they are also included in days"""

    name = models.CharField(max_length=100, default="mymeal")
    description = models.CharField(max_length=200, null=True)
    recipe = models.TextField(max_length=1000, null=True)
    url = models.URLField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    ingredients = models.ManyToManyField(Ingredient, through="ThroughMealIngr")
    fats = models.FloatField(default=0)
    protein = models.FloatField(default=0)
    carbs = models.FloatField(default=0)
    image = ResizedImageField(
        size=[1000, 1500],
        crop=["middle", "center"],
        default="foods/default_meal_thumbnail.jpg",
        upload_to=UploadAndRename("foods/meal_thumbnails"),
    )

    class Meta:
        """Set the ordering by pk"""

        ordering = ["pk"]

    def __str__(self) -> str:
        return f"{self.name}"

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Set the url for the meal and clean up old images"""
        image_clean_up(self)
        self.url = self.get_absolute_url()
        super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        """Generate the attribute url for the meal"""
        return reverse("foods_meal_detail", kwargs={"pk": self.pk})

    def save_ingredients(
        self, ingredients: Sequence[Ingredient], amounts: Sequence[float]
    ) -> None:
        """Create the necessary relations for ingredients"""
        for ingredient, amount in zip(ingredients, amounts):
            relation = ThroughMealIngr.objects.create(
                meal=self, ingredient=ingredient, amount=amount
            )
            self.fats += relation.fats
            self.carbs += relation.carbs
            self.protein += relation.protein
        self.save()


class ThroughMealIngr(models.Model):
    """Through model between meals and ingredients"""

    meal = models.ForeignKey(Meal, on_delete=CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=CASCADE)
    amount = models.FloatField()
    grams = models.PositiveIntegerField(default=0)
    fats = models.FloatField(default=0)
    protein = models.FloatField(default=0)
    carbs = models.FloatField(default=0)

    def __str__(self) -> str:
        return f"{self.meal},{self.ingredient}"

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Convert from native to grams"""
        self.grams = self.ingredient.convert_to_grams(self.amount)
        self.fats = round(self.ingredient.fats / 100 * self.grams, 2)
        self.protein = round(self.ingredient.protein / 100 * self.grams, 2)
        self.carbs = round(self.ingredient.carbs / 100 * self.grams, 2)
        super().save(*args, **kwargs)


class Day(models.Model):
    """The main field used to connect meals to users."""

    date = models.DateField(default=datetime.date.today)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    meals = models.ManyToManyField(Meal, through="ThroughDayMeal")
    backup = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.date},{self.author}"

    def save_meals(
        self, meals: Sequence[Meal], meal_nums: Sequence[int]
    ) -> None:
        """Create the necessary relations for meals"""
        for rel in ThroughDayMeal.objects.filter(day=self):
            rel.delete()
        for meal, meal_num in zip(meals, meal_nums):
            ThroughDayMeal.objects.create(
                day=self, meal=meal, meal_num=meal_num
            )

    def get_macros(self) -> list[float]:
        """Get the total calories from the meals"""
        relations = ThroughDayMeal.objects.filter(day=self)
        macros = [0.0, 0.0, 0.0, 0.0]
        for relation in relations:
            macros[0] += relation.meal.fats
            macros[1] += relation.meal.protein
            macros[2] += relation.meal.carbs

        macros[3] = macros[0] * 8 + macros[1] * 4 + macros[2] * 4
        return macros


class ThroughDayMeal(models.Model):
    """Through model between days and meals to denote meal numbers"""

    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    meal_num = models.PositiveSmallIntegerField()

    def __str__(self) -> str:
        return f"{self.day},{self.meal}"


class Diet(models.Model):
    """Diets have days, which are backups of the real days of the user"""

    name = models.CharField(max_length=100)
    public = models.BooleanField(default=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    end_date = models.DateField()
    description = models.TextField(max_length=200)
    days = models.ManyToManyField(Day)
    slug = models.SlugField(null=False, unique=True)

    class Meta:
        """Set the ordering by pk"""

        ordering = ["pk"]

    def __str__(self) -> str:
        return f"{self.date},{self.author}"

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Set the slug field, create days or the backups of the days"""
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        """Generate the url for foods_diet_details"""
        return reverse("foods_diet_detail", kwargs={"slug": self.slug})

    def get_import_url(self) -> str:
        """Generate the url for diet imports"""
        return reverse("foods_diet_import", kwargs={"slug": self.slug})

    def delete(self, *args: Any, **kwargs: Any) -> tuple[int, dict[str, int]]:
        """Delete the diet and the associated backup days"""
        for day in self.days.all():
            day.delete()
        return super().delete(*args, **kwargs)

    def save_days(self) -> None:
        """Create days or the backups of the days"""
        delta = (self.end_date - self.date).days + 1
        dates = (
            self.date + datetime.timedelta(days=date) for date in range(delta)
        )

        for date in dates:
            instance, created = Day.objects.get_or_create(
                date=date, author=self.author, backup=False
            )
            if created:
                instance.backup = True
                instance.save()
            else:
                relations = ThroughDayMeal.objects.filter(day=instance)
                instance.pk = None
                instance.backup = True
                instance.save()  # generates a new instance
                for relation in relations:
                    relation.pk = None
                    relation.day = instance
                    relation.save()

            self.days.add(instance)

    def fill_days(self, user: User, date: Any) -> None:
        """Fill the days of the `user` from `date` with the selected diet"""

        if isinstance(date, str):
            origin = datetime.datetime.strptime(date, "%Y-%m-%d")
        else:
            origin = date

        for delta in range(len(self.days.all())):
            date = origin + datetime.timedelta(days=delta)
            day = Day.objects.filter(date=date, author=user).first()
            if day:
                day.delete()

        for idx, day in enumerate(self.days.all()):
            relations = ThroughDayMeal.objects.filter(day=day)
            day.date = origin + datetime.timedelta(days=idx)
            day.backup = False
            day.author = user
            day.save()
            for relation in relations:
                relation.day = day

src/foods/views/diet_views.py
"""Views concerning diet creation & browsing"""
from typing import Any, cast
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.query import QuerySet
from django.http.request import HttpRequest
from django.http.response import Http404, HttpResponse
from django.shortcuts import render
from django.urls.base import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import DeleteView

from core.utils import PassUserFormView
from foods.forms import DietCreateForm, DietImportForm
from foods.models import Diet


class DietBrowse(ListView):
    """ListView for browsing different diets"""

    model = Diet
    context_object_name = "diets"
    template_name = "diet/browse.html"
    paginate_by = 10

    def get_queryset(self, *args: Any, **kwargs: Any) -> QuerySet:
        """Get only the public diets"""
        queryset = cast(QuerySet, super().get_queryset(*args, **kwargs))
        return queryset.filter(public=True)


browse = DietBrowse.as_view()


class DietDetail(DetailView):
    """DetailView for viewing a certain diet"""

    model = Diet
    context_object_name = "diet"
    template_name = "diet/view.html"


detail = DietDetail.as_view()


class DietCreate(SuccessMessageMixin, PassUserFormView):
    """FormView for creating a diet using the DietCreateForm"""

    form_class = DietCreateForm
    template_name = "diet/create.html"
    success_url = reverse_lazy("foods_day_create")
    success_message = "The diet has been created"


create = login_required(DietCreate.as_view())


class DietImport(SuccessMessageMixin, PassUserFormView):
    """A view for importing the diet, usually from a redirect with a slug"""

    form_class = DietImportForm
    template_name = "diet/import.html"
    success_url = reverse_lazy("foods_diet_browse")
    success_message = "Successfully imported the diet!"

    def get(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> HttpResponse:
        """Get the slug from the url"""
        diet = Diet.objects.filter(slug=kwargs.pop("slug")).first()
        if not diet:
            raise Http404

        context = self.get_context_data()
        context["diet"] = diet
        return render(request, self.template_name, context)


imprt = login_required(DietImport.as_view())


class DietDelete(SuccessMessageMixin, DeleteView):
    """A view for deleting a diet, usually from a redirect with a slug"""

    model = Diet
    context_object_name = "diet"
    template_name = "diet/delete.html"
    success_url = reverse_lazy("foods_diet_browse")
    success_message = "The diet has been deleted"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """If the person here isn't the author, it's fishy"""
        context = super().get_context_data(**kwargs)
        diet = context.get("diet")
        if not diet or self.request.user != diet.author:
            raise Http404
        return context


delete = login_required(DietDelete.as_view())

src/foods/templates/meal/create.html
{% extends 'general/base.html' %}
{% load static %}
{% block title %}New Meal{% endblock %}
{% block meals %}active{% endblock %}
{% block content %}
<div class="container" style="max-width: 100%;margin-top: 2%;">
	<form method="POST" enctype="multipart/form-data" autocomplete="OFF"><input class="form-control" type="hidden" id="amounts_form" value="" name="amounts"><input class="form-control" type="hidden" id="ingredients_form" value="" name="ingredient_data">
		{% csrf_token %}
		<div class="form-row">
			<div class="col-md-6" style="min-height: 800px;">
				<div id="info" style="box-shadow: 6px 6px 4px #e5e5e5;margin-bottom: 3%;display: flex;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;">
					<div style="display: grid;max-width: 70%;">
						<h1 style="font-size: 26px;font-family: 'Josefin Sans', sans-serif;color: #242e37;">Add a recipe here!</h1><span style="font-family: 'Josefin Sans', sans-serif;font-size: 18px;color: #969393;">Here you can create a meal which you can later use in different days and diets, have fun creating your own thing!</span>
					</div><img style="height: 35%;width: 35%;" src="{% static '/img/chef.png' %}">
				</div>
				<div style="height: 70px;box-shadow: 6px 6px 4px #e5e5e5;margin-bottom: 3%;display: flex;align-items: center;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;"><input class="form-control" type="text" id="id_name" placeholder="Name your dish" style="padding-left: 1%;width: 95%;font-family: 'Josefin Sans', sans-serif;text-align: left;border-style: none;border-bottom-style: none;font-size: 22px;color: #242e37;" name="name "maxlength="100" required=""><i class="fa fa-check" style="margin-left: 2%;margin-right: 2%;font-size: 31px;"></i></div>
				<div style="height: 70px;box-shadow: 6px 6px 4px #e5e5e5;margin-bottom: 3%;display: flex;align-items: center;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;"><input class="form-control" type="text" id="id_description" placeholder="A short description" style="padding-left: 1%;width: 95%;font-family: 'Josefin Sans', sans-serif;text-align: left;border-style: none;border-bottom-style: none;font-size: 22px;color: #242e37;" name="description" maxlength="200" required=""><i class="fa fa-file-text" style="margin-left: 2%;margin-right: 2%;font-size: 31px;"></i></div>
				<div>
					<div style="height: 70px;box-shadow: 6px 6px 4px #e5e5e5;margin-bottom: 3%;display: flex;align-items: center;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;"><input id="search__input" class="form-control" type="text" placeholder="Search for ingredients" style="padding-left: 1%;width: 95%;font-family: 'Josefin Sans', sans-serif;text-align: left;border-style: none;border-bottom-style: none;font-size: 22px;color: #242e37;" onkeyup="searchKeyUp()" onkeydown="searchKeyDown()">
						<div></div><i class="fa fa-search" style="margin-left: 2%;margin-right: 2%;font-size: 31px;"></i>
					</div>
					<div id="search_results" style="width: 95%;position: absolute;">
					</div>
				</div>
			</div>
			<div class="col-md-6" style="min-height: 800px;">
				<div id="ingredients-div" style="margin-bottom: 2%;box-shadow: 6px 6px 4px #eeeeee;display: grid;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;">
					<h1 style="width: 100%;font-size: 26px;font-family: 'Josefin Sans', sans-serif;color: #242e37;">Ingredients</h1>
					<div id="ingredients" style="border-radius: 10px;margin-top: 3%;min-height: 100px;background-color: white;border: 1px solid #f2f2f2;">
					</div>
				</div>
				<div id="Recipe" style="box-shadow: 6px 6px 4px #eeeeee;display: grid;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;">
					<div style="display: grid;max-width: 70%;">
						<h1 style="padding-left: 1%;font-size: 26px;font-family: 'Josefin Sans', sans-serif;color: #242e37;">The recipe content</h1>
					</div>
					<div style="border-radius: 10px;margin-top: 3%;min-height: 200px;background-color: white;border: 1px solid #f2f2f2;"><textarea class="form-control" id="id_recipe" style="padding: 2%;border-radius: 5px;border: hidden;width: 100%;height: 100%;background: #fff2f2;" placeholder="Whisk the eggs, comibne it with flour and dry yeast in a bowl. Mix it and let it sit for around 30 minutes (or just when it doubles in size). Then you will need to cut it into...." type="text" name="recipe" maxlength="200" required=""></textarea></div>
				</div>
				<div style="height: 70px;box-shadow: 6px 6px 4px #e5e5e5;margin-top: 3%;display: flex;align-items: center;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;"><input class="form-control-file" type="file" id="id_image" style="padding-left: 1%;width: 95%;font-family: 'Josefin Sans', sans-serif;text-align: left;border-style: none;border-bottom-style: none;color: #242e37;width: 95%;font-family: 'Merriweather Sans', sans-serif;font-size: 14px;" name="image" accept="image/*"><i class="fa fa-upload" style="margin-left: 2%;margin-right: 2%;font-size: 31px;"></i></div>
				<div class="text-center" style="margin-top: 3%;"><button class="btn btn-primary" type="submit" style="margin-bottom: 3%;background-color: #90c6c6;border-radius: 10px;min-width: 30%;font-family: Lato, sans-serif;font-size: 22px;border: 3px hidden rgb(255, 255, 255);" onclick="fillFields()">Submit</button></div>
			</div>
		</div>
	</form>
</div>
{% endblock %}
{% block js %}<script src="{% static '/js/meal/create.js' %}"></script>{% endblock %}

src/foods/templates/meal/delete.html
{% extends 'general/base.html' %}
{% load static %}
{% block title %}Meal Delete{%endblock%}
{% block meals %}active{%endblock%}
{% block content %}
<div class="container-fluid">
	<h3 class="text-dark mb-4">Meal Details</h3>
	<div class="row mb-3">
		<div class="col-lg-4">
			<div class="card mb-3">
				<div class="card-body text-center shadow"><img class="mb-3 mt-4" src="{{ meal.image.url }}" style="max-height: 216px;max-width: 385px;width: 100%;height: 100%;"></div>
			</div>
			<div id="ingredients-div" style="margin-bottom: 3%;box-shadow: 6px 6px 4px #eeeeee;display: grid;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;">
				<h1 style="width: 100%;font-size: 26px;font-family: 'Josefin Sans', sans-serif;color: #242e37;">Ingredients</h1>
				{%  for relation in ingredients  %}
				<div id="ingredients" style="border-radius: 10px;margin-top: 3%;min-height: 100px;background-color: white;border: 1px solid #f2f2f2;">
					<div id="ingredient-2" style="border: hidden;padding: 3%;display: grid;background: #e9f4f4;border-radius: 9px;">
						<div class="info" style="align-items: center;display: flex;height: 70px;"><img style="margin-right: 3%;margin-left: 2%;height: 60px;width: 60px;" src="{{ relation.ingredient.image.url }}">
							<div style="width: 60%;display: grid;"><span style="font-family: 'Josefin Sans', sans-serif;font-size: 25px;">{{ relation.ingredient.name }}</span>
								<div><i class="fa fa-fire" style="color: #ff9900;margin-right: 3%;"></i><small style="color: #757575;margin-right: 4%;font-family: 'Josefin Sans', sans-serif;font-size: 14.8px;">113 kcal</small><i class="fa fa-balance-scale" style="margin-right: 3%;color: rgb(255,29,124);"></i><small style="color: #757575;font-family: 'Josefin Sans', sans-serif;font-size: 14.8px;">100g</small></div>
							</div><textarea class="grams" style="color: #757575;padding: 1%;overflow: hidden!important;resize: none!important;height: 35px;border-radius: 13px;background-color: white;border: hidden;width: 15%;font-family: 'Josefin Sans', sans-serif;font-size: 21px;text-align: center;" readonly="">{{ relation.amount }}</textarea><span style="color: #757575;margin-left: 3%;">G</span>
						</div>
					</div>
				</div>
				{%  endfor  %}
			</div>
		</div>
		<div class="col-lg-8">
			<div class="row mb-3 d-none">
				<div class="col">
					<div class="card text-white bg-primary shadow">
						<div class="card-body">
							<div class="row mb-2">
								<div class="col">
									<p class="m-0">Peformance</p>
									<p class="m-0"><strong>65.2%</strong></p>
								</div>
								<div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
							</div>
							<p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last month</p>
						</div>
					</div>
				</div>
				<div class="col">
					<div class="card text-white bg-success shadow">
						<div class="card-body">
							<div class="row mb-2">
								<div class="col">
									<p class="m-0">Peformance</p>
									<p class="m-0"><strong>65.2%</strong></p>
								</div>
								<div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
							</div>
							<p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last month</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div style="height: 70px;box-shadow: 6px 6px 4px #e5e5e5;margin-bottom: 3%;display: flex;align-items: center;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;"><span style="padding-left: 1%;width: 95%;font-family: 'Josefin Sans', sans-serif;text-align: left;border-style: none;border-bottom-style: none;font-size: 22px;color: #242e37;">{{ meal.name }}</span><i class="fa fa-check" style="margin-left: 2%;margin-right: 2%;font-size: 31px;"></i></div>
					<div style="height: 70px;box-shadow: 6px 6px 4px #e5e5e5;margin-bottom: 3%;display: flex;align-items: center;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;"><span style="padding-left: 1%;width: 95%;font-family: 'Josefin Sans', sans-serif;text-align: left;border-style: none;border-bottom-style: none;font-size: 22px;color: #242e37;">{{ meal.description }}</span><i class="fa fa-file-text" style="margin-left: 2%;margin-right: 2%;font-size: 31px;"></i></div>
					<div class="card shadow">
						<ul class="list-group list-group-flush"></ul>
					</div>
					<div id="Recipe" style="box-shadow: 6px 6px 4px #eeeeee;display: grid;padding: 3%;border-radius: 10px;background-color: white;width: 100%;font-family: 'Merriweather Sans', sans-serif;border: 1px solid #f2f2f2;">
						<div style="display: grid;max-width: 70%;">
							<h1 style="padding-left: 1%;font-size: 26px;font-family: 'Josefin Sans', sans-serif;color: #242e37;">The recipe content</h1>
						</div>
						<div style="border-radius: 10px;margin-top: 3%;min-height: 200px;background-color: white;border: 1px solid #f2f2f2;"><textarea id="id_description" style="padding: 2%;border-radius: 5px;border: hidden;width: 100%;height: 100%;background: #fff2f2;" type="text" name="description" maxlength="200" readonly="">{{ meal.recipe }}</textarea></div>
						<form method="POST" autocomplete="OFF">
							{% csrf_token %}
							<div class="text-center" style="margin-top: 3%;"><button class="btn btn-primary" type="submit" style="margin-bottom: 3%;background-color: #90c6c6;border-radius: 10px;min-width: 30%;font-family: Lato, sans-serif;font-size: 22px;border: 3px hidden rgb(255, 255, 255);">Delete this meal</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}